// app/terms/page.jsx
import Link from "next/link";

export const metadata = {
  title: "Terms of Service — Smart SMB Hub",
  description: "Terms and conditions for using Smart SMB Hub.",
};

const sections = [
  {
    title: "1. Acceptance of Terms",
    text: "By accessing or using Smart SMB Hub (the \"Service\"), you agree to be bound by these Terms of Service (\"Terms\"). If you do not agree to these Terms, do not use the Service. These Terms apply to all users, including free trial users, paid subscribers, and Agency clients.",
  },
  {
    title: "2. Description of Service",
    text: "Smart SMB Hub is a multi-tenant SaaS platform that provides AI-powered tools for local small and medium-sized businesses, including an AI receptionist, workflow automations, document intelligence, lead management, and an analytics dashboard. We operate under the brand Smart SMB Hub, a product of Hasaan Labs LLC.",
  },
  {
    title: "3. Accounts & Registration",
    items: [
      "You must provide accurate, current, and complete information when creating an account.",
      "You are responsible for maintaining the confidentiality of your login credentials.",
      "You are responsible for all activity that occurs under your account.",
      "You must be at least 18 years old to create an account.",
      "You may not create an account on behalf of another person without authorization.",
      "We reserve the right to suspend or terminate accounts that violate these Terms.",
    ],
  },
  {
    title: "4. Free Trial",
    content: [
      {
        sub: "Trial Period",
        text: "We offer a 14-day free trial on Starter and Pro plans. No credit card is required to start. At the end of the trial period, you must subscribe to a paid plan to continue using the Service.",
      },
      {
        sub: "Trial Limitations",
        text: "Trial accounts are subject to usage limits. We reserve the right to modify, shorten, or discontinue the free trial at any time without notice.",
      },
    ],
  },
  {
    title: "5. Subscription & Billing",
    content: [
      {
        sub: "Plans",
        text: "Smart SMB Hub offers three plans: Starter ($97/mo), Pro ($197/mo), and Agency ($497/mo). All prices are in USD and subject to change with 30 days notice to existing subscribers.",
      },
      {
        sub: "Billing Cycle",
        text: "Subscriptions are billed monthly in advance. Your subscription automatically renews each month unless you cancel before the renewal date.",
      },
      {
        sub: "Cancellation",
        text: "You may cancel your subscription at any time from your billing settings. Cancellation takes effect at the end of your current billing period. We do not offer prorated refunds for unused portions of a billing period.",
      },
      {
        sub: "Refunds",
        text: "We offer a 7-day money-back guarantee on your first paid month if the Service does not meet your needs. After 7 days, all payments are non-refundable. Contact hasaank192@gmail.com to request a refund.",
      },
      {
        sub: "Payment Processor",
        text: "Payments are processed by Stripe. By subscribing, you agree to Stripe's Terms of Service and authorize recurring charges to your payment method.",
      },
    ],
  },
  {
    title: "6. Acceptable Use",
    text: "You agree not to use Smart SMB Hub to:",
    items: [
      "Violate any applicable law, regulation, or third-party rights",
      "Send spam, unsolicited messages, or harassing communications",
      "Upload or transmit malware, viruses, or malicious code",
      "Attempt to reverse engineer, scrape, or copy the platform",
      "Impersonate any person or entity",
      "Use the Service to compete directly with Smart SMB Hub",
      "Collect or harvest data from other users without consent",
      "Overload, disrupt, or interfere with our servers or network",
    ],
    footer: "Violation of these terms may result in immediate account suspension or termination.",
  },
  {
    title: "7. AI Features & Limitations",
    content: [
      {
        sub: "AI Accuracy",
        text: "Smart SMB Hub uses artificial intelligence to power features including the AI receptionist, workflow automations, and document intelligence. AI outputs may not always be accurate, complete, or appropriate. You are solely responsible for reviewing and acting on any AI-generated content.",
      },
      {
        sub: "Not Professional Advice",
        text: "Nothing generated by our AI constitutes legal, medical, financial, or professional advice. Do not rely on AI outputs as a substitute for licensed professional guidance.",
      },
      {
        sub: "Voice Calls",
        text: "If you use the AI voice receptionist feature, you are responsible for ensuring your use complies with applicable call recording, consent, and telecommunications laws in your jurisdiction.",
      },
    ],
  },
  {
    title: "8. Your Data & Content",
    content: [
      {
        sub: "Ownership",
        text: "You retain ownership of all data and content you upload or create within the platform (\"Your Content\"). You grant Hasaan Labs LLC a limited license to use Your Content solely to operate and improve the Service.",
      },
      {
        sub: "Responsibility",
        text: "You are solely responsible for the accuracy, legality, and appropriateness of Your Content. We are not liable for any content you upload or generate using the Service.",
      },
      {
        sub: "Data Portability",
        text: "Upon cancellation, you may request an export of your data within 30 days. After 90 days post-cancellation, your data may be permanently deleted.",
      },
    ],
  },
  {
    title: "9. Intellectual Property",
    text: "All rights, title, and interest in Smart SMB Hub — including the platform, code, design, branding, AI models, documentation, and trademarks — are and remain the exclusive property of Hasaan Labs LLC. Nothing in these Terms grants you any right to use our intellectual property except as expressly permitted to use the Service.",
  },
  {
    title: "10. Uptime & Service Availability",
    text: "We aim for high availability but do not guarantee 100% uptime. We are not liable for any loss or damage caused by downtime, service interruptions, or data loss. Planned maintenance will be communicated in advance when possible.",
  },
  {
    title: "11. Limitation of Liability",
    text: "To the maximum extent permitted by law, Hasaan Labs LLC shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or goodwill, arising out of or in connection with your use of the Service. Our total liability to you for any claims arising under these Terms shall not exceed the amount you paid us in the 3 months preceding the claim.",
  },
  {
    title: "12. Indemnification",
    text: "You agree to indemnify, defend, and hold harmless Hasaan Labs LLC and its officers, directors, employees, and agents from any claims, damages, losses, or expenses (including attorney's fees) arising from your use of the Service, Your Content, or your violation of these Terms.",
  },
  {
    title: "13. Termination",
    text: "We reserve the right to suspend or terminate your account at any time, with or without cause, with or without notice. Upon termination, your right to access the Service ceases immediately. Provisions of these Terms that by their nature should survive termination will survive.",
  },
  {
    title: "14. Governing Law",
    text: "These Terms are governed by the laws of the State of Maryland, United States, without regard to conflict of law principles. Any disputes arising under these Terms shall be resolved in the courts of Maryland or the federal courts located in the District of Columbia.",
  },
  {
    title: "15. Changes to Terms",
    text: "We may update these Terms at any time. We will notify you of material changes by email or by posting a notice on the platform with at least 14 days notice. Continued use of the Service after changes take effect constitutes acceptance of the revised Terms.",
  },
  {
    title: "16. Contact",
    text: "Questions about these Terms? Contact us at:",
    contact: {
      company: "Hasaan Labs LLC",
      location: "Washington, DC Metro Area",
      email: "hasaank192@gmail.com",
      website: "https://smartsmbhub.com",
    },
  },
];

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#060911] pt-24 pb-20 px-4 sm:px-6 lg:px-10">
      <div className="mx-auto max-w-[800px]">

        {/* Header */}
        <div className="mb-12 pb-8 border-b border-[#1A2540]">
          <div className="font-mono-custom text-[10px] text-[#F5A623] uppercase tracking-[3px] mb-4">Legal</div>
          <h1 className="font-syne text-[clamp(32px,5vw,56px)] font-extrabold tracking-tighter text-white mb-4">
            Terms of Service
          </h1>
          <p className="text-[#64748B] text-sm">
            Last updated: <strong className="text-[#94A3B8]">May 2026</strong>
          </p>
          <p className="text-[#64748B] text-[15px] mt-3 max-w-[580px]">
            Please read these Terms carefully before using Smart SMB Hub.
            By using the Service, you agree to be bound by these Terms.
          </p>
        </div>

        {/* Sections */}
        <div className="flex flex-col gap-10">
          {sections.map((section, i) => (
            <div key={i} className="flex flex-col gap-4">
              <h2 className="font-syne text-[18px] font-bold text-white">{section.title}</h2>

              {section.text && (
                <p className="text-[#94A3B8] text-[14px] leading-relaxed">{section.text}</p>
              )}

              {section.content && section.content.map((block, j) => (
                <div key={j} className="bg-[#0C1220] border border-[#1A2540] rounded-xl p-5">
                  <div className="text-[#F5A623] font-medium text-[13px] mb-1">{block.sub}</div>
                  <p className="text-[#94A3B8] text-[13px] leading-relaxed">{block.text}</p>
                </div>
              ))}

              {section.items && (
                <ul className="flex flex-col gap-2">
                  {section.items.map((item, j) => (
                    <li key={j} className="flex items-start gap-2 text-[14px] text-[#94A3B8]">
                      <span className="text-[#10B981] mt-px flex-shrink-0">+</span>
                      {item}
                    </li>
                  ))}
                </ul>
              )}

              {section.footer && (
                <p className="text-[#64748B] text-[13px] italic mt-1">{section.footer}</p>
              )}

              {section.contact && (
                <div className="bg-[#0C1220] border border-[#1A2540] rounded-xl p-5 flex flex-col gap-1 text-[13px]">
                  <div className="text-white font-semibold">{section.contact.company}</div>
                  <div className="text-[#64748B]">{section.contact.location}</div>
                  <a href={`mailto:${section.contact.email}`} className="text-[#F5A623] hover:underline">{section.contact.email}</a>
                  <a href={section.contact.website} className="text-[#64748B] hover:text-[#F5A623] transition">{section.contact.website}</a>
                </div>
              )}
            </div>
          ))}
        </div>

        {/* Footer nav */}
        <div className="mt-16 pt-8 border-t border-[#1A2540] flex flex-wrap gap-4 items-center justify-between">
          <Link href="/" className="text-[#64748B] text-sm hover:text-[#F5A623] transition">← Back to home</Link>
          <Link href="/privacy" className="text-[#64748B] text-sm hover:text-[#F5A623] transition">Privacy Policy →</Link>
        </div>
      </div>
    </div>
  );
}
